export default {
	"title": undefined,
	"field": undefined,
	"columns": undefined,
	"visible": undefined,
	"align": undefined,
	"vAlign": undefined,
	"width": undefined,
	"minWidth": 40,
	"maxWidth": undefined,
	"maxInitialWidth": undefined,
	"cssClass": undefined,
	"variableHeight": undefined,
	"headerValign": undefined,
	"headerAlign": undefined,
	"headerWordWrap": false,
	"editableTitle": undefined,
};
